// ── REPORT PDFs ─────────────────────────────────────────────────────────────
// The single-report PDF and the Year-End Tax Pack, drawn with the shared
// reportPdfKit. Report data comes from ReportsPage buildReportData:
// { title, kpis: [[label, value]], headers, rows, totals, note, sections }.

import { loadCdnScript } from './loadCdnScript'
import { createPdfWriter, loadPdfImage, hexToRgb, fitBox, PALETTE } from './reportPdfKit'

const JSPDF_CDN_URL = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'

export async function renderReportPDF({ title, kpis, headers, rows, totals, note, sections, reportName, company, period, companyColor, categoryAccent, logoUrl }) {
  await loadCdnScript(JSPDF_CDN_URL, 'jspdf')
  const { jsPDF } = window.jspdf
  const colCount = Math.max(headers?.length || 0, ...(sections || []).map(s => s.headers?.length || 0))
  const doc = new jsPDF({ orientation: colCount > 5 ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' })
  const [logo, mark] = await Promise.all([loadPdfImage(logoUrl), loadPdfImage('/icon-512.png', 256)])
  const name = reportName || title
  const coName = company || 'All companies'
  // Accent priority: company brand colour > report category accent > gold.
  const k = createPdfWriter(doc, { accent: hexToRgb(companyColor) || hexToRgb(categoryAccent), logo, mark, footerLabel: `${coName} - ${name}` })
  k.letterhead({ title: coName, subtitle: name, meta: [period, 'Generated ' + k.generatedOn()] })
  k.note(note)
  k.kpis(kpis || [])
  // One report can carry several titled tables (data.sections), e.g. the
  // Company P&L's "P&L lines" + "Shareholder split".
  if (sections && sections.length) sections.forEach(sec => { k.heading(sec.title); k.table(sec) })
  else k.table({ headers, rows, totals })
  k.finish()
  doc.save(`${name.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`)
}

// ── YEAR-END TAX PACK PDF ─────────────────────────────────────────────────────
// Single document: cover page with a contents list (page numbers filled in
// once the sections are laid out), then one section per report with its KPI
// tiles and tables. Same kit as the single-report PDF.
export async function renderYearEndPackPDF({ reports, company, companyColor, logoUrl, period }) {
  await loadCdnScript(JSPDF_CDN_URL, 'jspdf')
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const [logo, mark] = await Promise.all([loadPdfImage(logoUrl), loadPdfImage('/icon-512.png', 256)])
  const k = createPdfWriter(doc, { accent: hexToRgb(companyColor), logo, mark, footerLabel: `${company} - Year-End Tax Pack` })
  const { W, H, M, CW, font, text } = k
  const P = PALETTE

  const starts = []
  for (const rep of reports) {
    const d = rep.data
    k.newPage()
    starts.push(k.currentPage())
    k.sectionBand(rep.name, `${company} - ${period}`)
    if (!d) { font(9, 'italic', P.faint); text('No data for this period.', M, k.y + 4); continue }
    k.note(d.note)
    k.kpis(d.kpis || [])
    if (d.sections?.length) d.sections.forEach(sec => { k.heading(sec.title); k.table(sec) })
    else k.table({ headers: d.headers || [], rows: d.rows || [], totals: d.totals })
  }

  // ── Cover (page 1) ─────────────────────────────────────────────────────
  doc.setPage(1)
  doc.setFillColor(...k.accent); doc.rect(0, 0, W, 4, 'F')
  let y = 28
  if (logo) {
    const box = fitBox(logo.w, logo.h, 46, 46)
    k.drawImage(logo, M, y, box.w, box.h)
    y += box.h + 16
  } else y += 20
  font(30, 'bold'); text('Year-End Tax Pack', M, y)
  font(13, 'normal', P.muted); text(company, M, y + 10)
  font(11, 'normal', P.muted); text(period, M, y + 17)
  doc.setFillColor(...k.accent); doc.rect(M, y + 23, 40, 1, 'F')

  y += 40
  font(8, 'bold', P.muted); text('CONTENTS', M, y)
  y += 8
  reports.forEach((r, i) => {
    font(10.5, 'normal', P.faint); text(`${i + 1}`, M, y)
    font(10.5, 'normal', P.ink); text(r.name, M + 8, y)
    const nameEnd = M + 8 + doc.getTextWidth(r.name) + 3
    const pageTxt = String(starts[i])
    font(10.5, 'normal', P.muted); const pw = doc.getTextWidth(pageTxt)
    text(pageTxt, W - M, y, { align: 'right' })
    doc.setDrawColor(...P.border); doc.setLineWidth(0.3); doc.setLineDashPattern([0.4, 1.4], 0)
    doc.line(nameEnd, y - 0.6, W - M - pw - 3, y - 0.6)
    doc.setLineDashPattern([], 0)
    y += 9
  })

  font(8, 'normal', P.faint)
  text(doc.splitTextToSize(`Pass this pack to your accountant for self-assessment (SA105). Generated on ${k.generatedOn()}.`, CW), M, H - 30)
  if (mark) k.drawImage(mark, M, H - 20, 5, 5)
  font(7.5, 'bold', P.slate); text('Generated by Properly', M + (mark ? 7 : 0), H - 16.6)
  font(7, 'normal', P.faint); text('ownproperly.com', M + (mark ? 7 : 0), H - 13.2)

  k.skipFooterOn(1)
  k.finish()
  doc.save(`year-end-tax-pack-${company.replace(/[^a-zA-Z0-9]/g,'-').toLowerCase()}-${period.replace(/[^a-zA-Z0-9]/g,'-')}.pdf`)
}
