-- ⚠️ DRAFT — NOT YET APPLIED TO PRODUCTION
--
-- Generated by the overnight schema audit. See OVERNIGHT_AUDIT.md
-- "Database schema + RLS audit", finding #1.
--
-- This migration enables RLS and adds per-user policies on 20 application
-- tables that currently have NO row-level security in their migration
-- history. Without RLS, any authenticated user can read/write all rows
-- across all companies on these tables.
--
-- Before applying:
--   1. Read each policy below carefully. The scope column (user_id,
--      property_id, company_id, etc.) may not match how YOUR app actually
--      reads the table. Adjust the USING clause per-table.
--   2. Some tables (e.g. admin_announcements, feature_flag_*) are
--      INTENTIONALLY readable by all signed-in users. For those, the
--      policy should be `USING (auth.role() = 'authenticated')` not the
--      ownership check below.
--   3. Some tables hold tenant data (tenant_messages, tenant_profiles).
--      Tenants reading their own data + landlords reading any tenant on
--      their property is a more complex policy than the default below.
--   4. Apply on a staging branch first — Supabase has a "preview branch"
--      feature that's safer than applying to prod directly.
--
-- This file is named with a leading underscore so it doesn't run via
-- `supabase db push`. Rename to drop the underscore once reviewed.

-- ── Helper assumptions ─────────────────────────────────────────────────
-- All policies below assume the following functions already exist (they
-- do — defined in row-level-security.sql):
--   is_developer()                  → bool
--   has_company_access(uuid)        → bool  -- user owns or has shared
--                                              access to the company
--   has_property_access(uuid)       → bool  -- via the property's company

-- ────────────────────────────────────────────────────────────────────────
-- USER-SCOPED tables (user_id column on the row)
-- ────────────────────────────────────────────────────────────────────────

-- property_notes — per-property notes left by landlords
alter table public.property_notes enable row level security;
drop policy if exists "property_notes_all" on public.property_notes;
create policy "property_notes_all" on public.property_notes for all
  using (is_developer() or user_id = auth.uid() or has_property_access(property_id))
  with check (is_developer() or user_id = auth.uid() or has_property_access(property_id));

-- referrals — user's own referral records
alter table public.referrals enable row level security;
drop policy if exists "referrals_all" on public.referrals;
create policy "referrals_all" on public.referrals for all
  using (is_developer() or user_id = auth.uid())
  with check (is_developer() or user_id = auth.uid());

-- address_book — user's saved contractors / contacts
alter table public.address_book enable row level security;
drop policy if exists "address_book_all" on public.address_book;
create policy "address_book_all" on public.address_book for all
  using (is_developer() or user_id = auth.uid())
  with check (is_developer() or user_id = auth.uid());

-- admin_notes — admin's own internal notes about other users
alter table public.admin_notes enable row level security;
drop policy if exists "admin_notes_select" on public.admin_notes;
create policy "admin_notes_select" on public.admin_notes for select
  using (is_developer());
drop policy if exists "admin_notes_insert" on public.admin_notes;
create policy "admin_notes_insert" on public.admin_notes for insert
  with check (is_developer());
drop policy if exists "admin_notes_update" on public.admin_notes;
create policy "admin_notes_update" on public.admin_notes for update
  using (is_developer());
drop policy if exists "admin_notes_delete" on public.admin_notes;
create policy "admin_notes_delete" on public.admin_notes for delete
  using (is_developer());

-- invitations — per-email invites a user has issued
alter table public.invitations enable row level security;
drop policy if exists "invitations_select" on public.invitations;
create policy "invitations_select" on public.invitations for select
  using (is_developer() or invited_by = auth.uid() or email = auth.email());
drop policy if exists "invitations_insert" on public.invitations;
create policy "invitations_insert" on public.invitations for insert
  with check (invited_by = auth.uid());
drop policy if exists "invitations_update" on public.invitations;
create policy "invitations_update" on public.invitations for update
  using (is_developer() or invited_by = auth.uid() or email = auth.email());
drop policy if exists "invitations_delete" on public.invitations;
create policy "invitations_delete" on public.invitations for delete
  using (is_developer() or invited_by = auth.uid());

-- ────────────────────────────────────────────────────────────────────────
-- PROPERTY-SCOPED tables (property_id → joins to company access)
-- ────────────────────────────────────────────────────────────────────────

-- refurb_phases — refurbishment phases on a property
alter table public.refurb_phases enable row level security;
drop policy if exists "refurb_phases_all" on public.refurb_phases;
create policy "refurb_phases_all" on public.refurb_phases for all
  using (is_developer() or has_property_access(property_id))
  with check (is_developer() or has_property_access(property_id));

-- refurb_costs — itemised refurb line items
alter table public.refurb_costs enable row level security;
drop policy if exists "refurb_costs_all" on public.refurb_costs;
create policy "refurb_costs_all" on public.refurb_costs for all
  using (is_developer() or has_property_access(property_id))
  with check (is_developer() or has_property_access(property_id));

-- rent_history — rent change history per property
alter table public.rent_history enable row level security;
drop policy if exists "rent_history_all" on public.rent_history;
create policy "rent_history_all" on public.rent_history for all
  using (is_developer() or has_property_access(property_id))
  with check (is_developer() or has_property_access(property_id));

-- rent_increases — scheduled rent increases
alter table public.rent_increases enable row level security;
drop policy if exists "rent_increases_all" on public.rent_increases;
create policy "rent_increases_all" on public.rent_increases for all
  using (is_developer() or has_property_access(property_id))
  with check (is_developer() or has_property_access(property_id));

-- lettings_progressions — vacancy-to-move-in pipeline per property
alter table public.lettings_progressions enable row level security;
drop policy if exists "lettings_progressions_all" on public.lettings_progressions;
create policy "lettings_progressions_all" on public.lettings_progressions for all
  using (is_developer() or has_property_access(property_id))
  with check (is_developer() or has_property_access(property_id));

-- ────────────────────────────────────────────────────────────────────────
-- COMPANY-SCOPED tables (company_id → joins to company access)
-- ────────────────────────────────────────────────────────────────────────

-- subscriptions — Stripe subscription per company
alter table public.subscriptions enable row level security;
drop policy if exists "subscriptions_select" on public.subscriptions;
create policy "subscriptions_select" on public.subscriptions for select
  using (is_developer() or has_company_access(company_id));
-- Only service role / webhooks should INSERT/UPDATE billing rows.
-- (No INSERT/UPDATE policy = client cannot modify — service_role bypasses)
drop policy if exists "subscriptions_delete" on public.subscriptions;
create policy "subscriptions_delete" on public.subscriptions for delete
  using (is_developer());

-- company_documents — files attached at the company level
alter table public.company_documents enable row level security;
drop policy if exists "company_documents_all" on public.company_documents;
create policy "company_documents_all" on public.company_documents for all
  using (is_developer() or has_company_access(company_id))
  with check (is_developer() or has_company_access(company_id));

-- ────────────────────────────────────────────────────────────────────────
-- INSURANCE — policies + join table
-- ────────────────────────────────────────────────────────────────────────

alter table public.insurance_policies enable row level security;
drop policy if exists "insurance_policies_all" on public.insurance_policies;
create policy "insurance_policies_all" on public.insurance_policies for all
  using (is_developer() or user_id = auth.uid() or has_company_access(company_id))
  with check (is_developer() or user_id = auth.uid() or has_company_access(company_id));

-- The join table — gated by access to the policy itself
alter table public.insurance_policy_properties enable row level security;
drop policy if exists "insurance_policy_properties_all" on public.insurance_policy_properties;
create policy "insurance_policy_properties_all" on public.insurance_policy_properties for all
  using (
    is_developer() or exists (
      select 1 from public.insurance_policies p
      where p.id = policy_id
      and (p.user_id = auth.uid() or has_company_access(p.company_id))
    )
  )
  with check (
    is_developer() or exists (
      select 1 from public.insurance_policies p
      where p.id = policy_id
      and (p.user_id = auth.uid() or has_company_access(p.company_id))
    )
  );

-- ────────────────────────────────────────────────────────────────────────
-- DEALS — pipeline tables
-- ────────────────────────────────────────────────────────────────────────

-- deal_contacts — contacts attached to a deal
alter table public.deal_contacts enable row level security;
drop policy if exists "deal_contacts_all" on public.deal_contacts;
create policy "deal_contacts_all" on public.deal_contacts for all
  using (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  )
  with check (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  );

-- deal_documents — files attached to a deal
alter table public.deal_documents enable row level security;
drop policy if exists "deal_documents_all" on public.deal_documents;
create policy "deal_documents_all" on public.deal_documents for all
  using (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  )
  with check (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  );

-- deal_milestones — checklist items per deal
alter table public.deal_milestones enable row level security;
drop policy if exists "deal_milestones_all" on public.deal_milestones;
create policy "deal_milestones_all" on public.deal_milestones for all
  using (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  )
  with check (
    is_developer() or exists (
      select 1 from public.deals d
      where d.id = deal_id and (d.user_id = auth.uid() or has_company_access(d.company_id))
    )
  );

-- ────────────────────────────────────────────────────────────────────────
-- TENANT-FACING tables — more nuanced: tenant reads own, landlord reads any
-- ────────────────────────────────────────────────────────────────────────

-- tenant_profiles — a tenant's profile (linked to a property + auth user)
alter table public.tenant_profiles enable row level security;
drop policy if exists "tenant_profiles_select" on public.tenant_profiles;
create policy "tenant_profiles_select" on public.tenant_profiles for select
  using (
    is_developer()
    or user_id = auth.uid()                    -- the tenant themselves
    or has_property_access(property_id)        -- the landlord
  );
drop policy if exists "tenant_profiles_insert" on public.tenant_profiles;
create policy "tenant_profiles_insert" on public.tenant_profiles for insert
  with check (user_id = auth.uid() or has_property_access(property_id));
drop policy if exists "tenant_profiles_update" on public.tenant_profiles;
create policy "tenant_profiles_update" on public.tenant_profiles for update
  using (
    is_developer()
    or user_id = auth.uid()
    or has_property_access(property_id)
  );
drop policy if exists "tenant_profiles_delete" on public.tenant_profiles;
create policy "tenant_profiles_delete" on public.tenant_profiles for delete
  using (is_developer() or has_property_access(property_id));

-- tenant_messages — messages between tenant and landlord
alter table public.tenant_messages enable row level security;
drop policy if exists "tenant_messages_select" on public.tenant_messages;
create policy "tenant_messages_select" on public.tenant_messages for select
  using (
    is_developer()
    or sender_id = auth.uid()
    or recipient_id = auth.uid()
    or has_property_access(property_id)
  );
drop policy if exists "tenant_messages_insert" on public.tenant_messages;
create policy "tenant_messages_insert" on public.tenant_messages for insert
  with check (sender_id = auth.uid());
drop policy if exists "tenant_messages_update" on public.tenant_messages;
create policy "tenant_messages_update" on public.tenant_messages for update
  using (
    is_developer()
    or sender_id = auth.uid()
    or recipient_id = auth.uid()
    or has_property_access(property_id)
  );
drop policy if exists "tenant_messages_delete" on public.tenant_messages;
create policy "tenant_messages_delete" on public.tenant_messages for delete
  using (is_developer() or sender_id = auth.uid());

-- ────────────────────────────────────────────────────────────────────────
-- PUBLIC-READABLE tables — broadcast content for all signed-in users
-- ────────────────────────────────────────────────────────────────────────

-- admin_announcements — platform-wide announcements shown in the banner.
-- All authenticated users can READ; only developers can write.
alter table public.admin_announcements enable row level security;
drop policy if exists "admin_announcements_select" on public.admin_announcements;
create policy "admin_announcements_select" on public.admin_announcements for select
  using (auth.role() = 'authenticated');
drop policy if exists "admin_announcements_insert" on public.admin_announcements;
create policy "admin_announcements_insert" on public.admin_announcements for insert
  with check (is_developer());
drop policy if exists "admin_announcements_update" on public.admin_announcements;
create policy "admin_announcements_update" on public.admin_announcements for update
  using (is_developer());
drop policy if exists "admin_announcements_delete" on public.admin_announcements;
create policy "admin_announcements_delete" on public.admin_announcements for delete
  using (is_developer());

-- ────────────────────────────────────────────────────────────────────────
-- VERIFICATION QUERIES — run after applying to confirm
-- ────────────────────────────────────────────────────────────────────────
-- SELECT tablename, rowsecurity
-- FROM pg_tables
-- WHERE schemaname = 'public'
-- ORDER BY rowsecurity ASC, tablename;
--
-- All rows should now show rowsecurity = true.
