#!/usr/bin/env python3
"""Generate scripts/demo/seed.sql: a fictional two-company portfolio for the
Properly demo account, used for marketing screenshots.

Everything is deterministic (fixed seed, uuid5 ids) so the seed can be re-run
after teardown.sql and produce the same rows. Nothing here is real: the
companies, addresses, people and figures are invented.

Run:  python3 scripts/demo/generate_seed.py > scripts/demo/seed.sql
"""
import random, uuid, datetime as dt, json

random.seed(7)
NS = uuid.UUID('de3d0000-0000-4000-8000-00000000f00d')
def uid(*parts):
    return str(uuid.uuid5(NS, '|'.join(str(p) for p in parts)))

U   = 'fb1e99c8-ef2f-4903-9bbf-588ead787a6d'        # demo auth user
C1  = 'de3d0000-0000-4000-8000-000000000001'        # Northgate Property Ltd
C2  = 'de3d0000-0000-4000-8000-000000000002'        # Harbour Lets Ltd
HC  = 'de3d0002-0000-4000-8000-000000000001'        # hostaway connection
MGR = 'de3d0003-0000-4000-8000-000000000001'        # STL manager
TODAY = dt.date(2026, 9, 7)

def q(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, (dt.date, dt.datetime)): return "'" + v.isoformat() + "'"
    if isinstance(v, (dict, list)): return "'" + json.dumps(v).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"

out = []
def section(title): out.append(f"\n-- ── {title} " + "─" * max(0, 70 - len(title)))
def insert(table, rows, cols=None):
    if not rows: return
    cols = cols or list(rows[0].keys())
    out.append(f"insert into public.{table} ({', '.join(cols)}) values")
    # A key the row does not carry becomes DEFAULT, not NULL: an explicit null
    # overrides the column default and trips NOT NULL columns such as
    # tenancies.opening_arrears or properties.is_hmo.
    vals = [f"  ({', '.join(q(r[c]) if c in r else 'default' for c in cols)})" for r in rows]
    out.append(',\n'.join(vals) + ';')

def insert_compact(table, rows, cols, types, consts):
    """insert ... select <consts>, v.* from (values ...) with explicit casts, for
    the two bulk tables. Keeps the repeated constants out of every row."""
    if not rows: return
    const_cols = ', '.join(consts.keys()); const_vals = ', '.join(consts.values())
    casts = ', '.join(f"v.{c}::{types[c]}" for c in cols)
    out.append(f"insert into public.{table} ({const_cols}, {', '.join(cols)})\nselect {const_vals}, {casts} from (values")
    out.append(',\n'.join('  (' + ', '.join(q(r.get(c)) for c in cols) + ')' for r in rows))
    out.append(f") as v({', '.join(cols)});")

out.append("-- GENERATED by scripts/demo/generate_seed.py. Do not edit by hand.")
out.append(f"-- Demo user {U}. Teardown: scripts/demo/teardown.sql")

# ── Companies, access, billing, profile ─────────────────────────────────────
section('companies')
insert('companies', [
  dict(id=C1, user_id=U, owner_id=U, name='Northgate Property Ltd', abbr='NGP', color='#4B8FE0', is_free_tier=True, free_tier_reason='Demo account', free_tier_granted_by=U, contact_mode='landlord', subdomain='northgate', company_type='operating'),
  dict(id=C2, user_id=U, owner_id=U, name='Harbour Lets Ltd', abbr='HBL', color='#9B6FDE', is_free_tier=True, free_tier_reason='Demo account', free_tier_granted_by=U, contact_mode='landlord', company_type='operating'),
])
insert('user_company_access', [
  dict(id=uid('uca', C1), user_id=U, company_id=C1, email='justin+demo@forta.productions', is_admin=True, is_owner=True, role='editor', permissions={}),
  dict(id=uid('uca', C2), user_id=U, company_id=C2, email='justin+demo@forta.productions', is_admin=True, is_owner=True, role='editor', permissions={}),
])
insert('subscriptions', [
  dict(id=uid('sub', C1), company_id=C1, owner_id=U, status='active', tier='investor', property_count=13, current_period_start=dt.datetime(2026, 8, 28, 9, 0), current_period_end=dt.datetime(2026, 9, 28, 9, 0)),
  dict(id=uid('sub', C2), company_id=C2, owner_id=U, status='active', tier='investor', property_count=6, current_period_start=dt.datetime(2026, 8, 28, 9, 0), current_period_end=dt.datetime(2026, 9, 28, 9, 0)),
])
insert('company_settings', [
  dict(id=uid('cs', C1), company_id=C1, user_id=U, feature_compliance=True, feature_tenancy=True, feature_maintenance=True, feature_documents=True, feature_expenses=True, feature_reports=True, feature_statements=True, feature_tenant_portal=True, feature_tenant_messaging=True, feature_tenant_repairs=True, feature_tenant_documents=True, year_type='tax', bank_reference_prefix='NGP', report_accent_color='#4B8FE0'),
  dict(id=uid('cs', C2), company_id=C2, user_id=U, feature_compliance=True, feature_tenancy=True, feature_maintenance=True, feature_documents=True, feature_expenses=True, feature_reports=True, feature_statements=False, feature_tenant_portal=False, feature_tenant_messaging=False, feature_tenant_repairs=False, feature_tenant_documents=False, year_type='tax', bank_reference_prefix='HBL', report_accent_color='#9B6FDE'),
])
out.append(f"""insert into public.user_profiles (id, user_id, email, full_name, first_name, last_name, onboarding_completed, onboarding_completed_at, account_type, nav_items, dark_mode)
values ({q(uid('profile', U))}, {q(U)}, 'justin+demo@forta.productions', 'Sam Whitfield', 'Sam', 'Whitfield', true, now(), 'limited_company',
        '["dashboard","properties","refurbs","rent","stl","reports","mtd","compliance","deals","settings","seen:refurbs"]'::jsonb, false)
on conflict (user_id) do update set onboarding_completed = true, nav_items = excluded.nav_items, full_name = excluded.full_name;""")
insert('rra_compliance', [
  dict(id=uid('rra', C1), company_id=C1, user_id=U, prs_registered=True, prs_reference='PRS-NE-004471', ombudsman_registered=True, ombudsman_reference='PRS-OMB-22-8814', periodic_converted=True, periodic_converted_at=dt.date(2026, 6, 1)),
  dict(id=uid('rra', C2), company_id=C2, user_id=U, prs_registered=False, ombudsman_registered=False, periodic_converted=False),
])

# ── Properties ──────────────────────────────────────────────────────────────
section('properties')
P = {}
def prop(key, **kw):
    kw.setdefault('user_id', U); kw.setdefault('geocode_status', 'ok'); kw.setdefault('geocoded_at', dt.datetime(2026, 8, 1, 6, 0))
    kw.setdefault('refurb_cost', 0); kw.setdefault('arrears', 0); kw.setdefault('managed_by', '')
    kw.setdefault('is_hmo', False); kw.setdefault('refurb_cost_unpaid', False)  # NOT NULL columns; an explicit null beats the default
    kw['id'] = f"de3d0001-0000-4000-8000-0000000000{key:02d}"
    P[key] = kw; return kw

ELM = 'Elmfield House, Roker Avenue, Sunderland, SR6 0HN'
prop(1,  company_id=C1, name='14 Ashworth Road', address='14 Ashworth Road, Sunderland, SR4 7QT', prop_type='3-Bed House', status='rented', rent_pcm=725, rent_due_day='1st', tenant_name='Claire Robson', tenant_since=dt.date(2024, 3, 1), purchase_price=98000, purchase_date=dt.date(2022, 5, 20), current_value=118000, est_value=118000, deposit=24500, stamp_duty=2940, legal_fees=1150, mortgage_amount=73500, mortgage_rate=4.89, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=299.55, mortgage_product_end_date=dt.date(2026, 12, 1), insurance=310, epc_rating='C', epc_expiry_date=dt.date(2032, 4, 10), epc_certificate_number='8801-2204-7300-0110-2026', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.9052, longitude=-1.4021, refurb_status='complete')
prop(2,  company_id=C1, name='27 Hillcrest Avenue', address='27 Hillcrest Avenue, Durham, DH1 5PN', prop_type='2-Bed House', status='rented', rent_pcm=850, rent_due_day='14th', tenant_name='Daniel & Priya Mehta', tenant_since=dt.date(2025, 6, 14), purchase_price=142000, purchase_date=dt.date(2025, 4, 11), current_value=152000, est_value=152000, deposit=35500, stamp_duty=7100, legal_fees=1320, mortgage_amount=106500, mortgage_rate=5.14, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=456.18, mortgage_product_end_date=dt.date(2030, 4, 30), insurance=345, epc_rating='D', epc_expiry_date=dt.date(2033, 1, 22), epc_certificate_number='8801-2204-7300-0110-2027', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.7862, longitude=-1.5563, refurb_status='complete')
prop(3,  company_id=C1, name='9 Ferndale Terrace', address='9 Ferndale Terrace, Sunderland, SR2 8JR', prop_type='2-Bed House', status='rented', rent_pcm=695, rent_due_day='1st', tenant_name='Tom Ashby', tenant_since=dt.date(2023, 11, 1), arrears=1785, purchase_price=84000, purchase_date=dt.date(2021, 9, 3), current_value=102000, est_value=102000, deposit=21000, stamp_duty=2520, legal_fees=980, mortgage_amount=63000, mortgage_rate=3.29, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=172.73, mortgage_product_end_date=dt.date(2026, 10, 31), insurance=290, epc_rating='D', epc_expiry_date=dt.date(2031, 8, 30), epc_certificate_number='8801-2204-7300-0110-2028', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.8971, longitude=-1.3762, refurb_status='complete', refurb_cost=3200)
prop(4,  company_id=C1, name='41 Kestrel Way', address='41 Kestrel Way, Washington, NE38 8QL', prop_type='3-Bed Semi House', status='notice_given', rent_pcm=795, rent_due_day='15th', tenant_name='Gemma Lawson', tenant_since=dt.date(2022, 8, 15), purchase_price=128000, purchase_date=dt.date(2020, 2, 28), current_value=149000, est_value=149000, deposit=32000, stamp_duty=3840, legal_fees=1100, mortgage_amount=96000, mortgage_rate=2.19, mortgage_term=25, mortgage_type='repayment', mortgage_monthly_payment=416.02, mortgage_product_end_date=dt.date(2027, 2, 28), insurance=330, epc_rating='C', epc_expiry_date=dt.date(2030, 2, 14), epc_certificate_number='8801-2204-7300-0110-2029', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.9048, longitude=-1.5351, refurb_status='complete')
prop(5,  company_id=C1, name='3 Mariners Court', address='3 Mariners Court, Seaham, SR7 7FD', prop_type='2-Bed Flat', status='vacant', vacant_since=dt.date(2026, 8, 15), rent_pcm=650, rent_due_day='1st', purchase_price=89500, purchase_date=dt.date(2023, 3, 17), current_value=96000, est_value=96000, deposit=22500, stamp_duty=2685, legal_fees=1040, mortgage_amount=67000, mortgage_rate=5.45, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=304.27, mortgage_product_end_date=dt.date(2028, 3, 31), insurance=0, epc_rating='C', epc_expiry_date=dt.date(2033, 3, 2), epc_certificate_number='8801-2204-7300-0110-2030', epc_sync_status='found', has_gas_supply=False, heating_type='electric', latitude=54.8383, longitude=-1.3362, refurb_status='complete')
flat_rent = {1: 550, 2: 575, 3: 550, 4: None, 5: 595, 6: 565}
flat_ten  = {1: ('Aisha Khan', dt.date(2024, 9, 1)), 2: ('Ryan Cole', dt.date(2025, 2, 1)), 3: ('Margaret Ellis', dt.date(2023, 5, 1)), 5: ('Lewis & Beth Turner', dt.date(2026, 4, 1)), 6: ('Sophie Grant', dt.date(2025, 11, 15))}
flat_epc  = {1: 'C', 2: 'C', 3: 'D', 4: 'E', 5: 'C', 6: 'D'}
for f in range(1, 7):
    k = 5 + f
    t = flat_ten.get(f)
    prop(k, company_id=C1, name=f'Flat {f}, Elmfield House', address=f'Flat {f}, {ELM}', prop_type='1-Bed Flat',
         status='refurb' if f == 4 else 'rented', refurb_status='in-progress' if f == 4 else 'complete',
         rent_pcm=flat_rent[f] or 595, rent_due_day='1st', tenant_name=t[0] if t else None, tenant_since=t[1] if t else None,
         purchase_price=60833, purchase_date=dt.date(2023, 5, 1), current_value=72000, est_value=72000, deposit=15208, stamp_duty=1825, legal_fees=420,
         mortgage_amount=45625, mortgage_rate=5.6, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=212.92, mortgage_product_end_date=dt.date(2028, 4, 30), insurance=0,
         epc_rating=flat_epc[f], epc_expiry_date=dt.date(2033, 5, 20), epc_certificate_number=f'8801-2204-7300-0110-30{f:02d}', epc_sync_status='found', has_gas_supply=True, heating_type='gas',
         latitude=54.9181 + f * 0.00002, longitude=-1.3712, refurb_cost=8500 if f == 4 else 0, arrears=275 if f == 2 else 0)
prop(12, company_id=C1, name='22 Brunswick Street', address='22 Brunswick Street, Sunderland, SR1 3DL', prop_type='5-Bed HMO', status='rented', is_hmo=True, licensing_scheme='mandatory_hmo', rent_pcm=2150, rent_due_day='1st', tenant_name='5 rooms, let by the room', tenant_since=dt.date(2024, 3, 1), purchase_price=165000, purchase_date=dt.date(2024, 1, 19), current_value=190000, est_value=190000, deposit=41250, stamp_duty=5450, legal_fees=1650, mortgage_amount=123750, mortgage_rate=6.05, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=623.91, mortgage_product_end_date=dt.date(2029, 1, 31), insurance=620, epc_rating='D', epc_expiry_date=dt.date(2034, 1, 8), epc_certificate_number='8801-2204-7300-0110-2031', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.9063, longitude=-1.3834, refurb_status='complete')
prop(13, company_id=C1, name='8 Orchard Close', address='8 Orchard Close, Chester-le-Street, DH3 3RB', prop_type='3-Bed House', status='refurb', refurb_status='in-progress', rent_pcm=895, rent_due_day='1st', purchase_price=112000, purchase_date=dt.date(2026, 8, 1), current_value=140000, est_value=140000, deposit=112000, stamp_duty=5600, legal_fees=1280, mortgage_amount=0, mortgage_rate=0, mortgage_term=25, refurb_cost=24000, refurb_cost_unpaid=True, insurance=0, epc_rating='E', epc_expiry_date=dt.date(2029, 7, 15), epc_certificate_number='8801-2204-7300-0110-2032', epc_sync_status='found', has_gas_supply=True, heating_type='gas', latitude=54.8583, longitude=-1.5742)
QL = 'The Quayside Lofts, Low Street, Sunderland, SR1 2AR'
for r in range(1, 7):
    prop(20 + r, company_id=C2, name=f'Room {r}, The Quayside Lofts', address=f'Room {r}, {QL}', prop_type='Serviced Apartment', status='short_term_let', refurb_status='complete', rent_pcm=0, rent_due_day='',
         purchase_price=78000, purchase_date=dt.date(2024, 6, 14), current_value=95000, est_value=95000, deposit=23400, stamp_duty=2340, legal_fees=560,
         mortgage_amount=54600, mortgage_rate=5.35, mortgage_term=25, mortgage_type='interest_only', mortgage_monthly_payment=243.43, mortgage_product_end_date=dt.date(2029, 6, 30), insurance=0,
         epc_rating='C', epc_expiry_date=dt.date(2034, 6, 30), epc_certificate_number=f'8801-2204-7300-0110-40{r:02d}', epc_sync_status='found', has_gas_supply=False, heating_type='electric',
         latitude=54.9112 + r * 0.00002, longitude=-1.3811, stl_manager_id=MGR)
# The STL manager must exist before the rooms that reference it (FK).
insert('stl_managers', [dict(id=MGR, company_id=C2, user_id=U, name='Harbour Hosts (Kate Reynolds)', percentage=12, basis='net_after_platform_fees', payout_frequency='fortnightly', active=True, created_by=U, notes='Cleaning and guest comms. Paid every other Friday.')])
insert('properties', list(P.values()), cols=sorted({c for p in P.values() for c in p}))
def pid(k): return P[k]['id']

# EPC register rows
section('epc_certificates')
insert('epc_certificates', [dict(id=uid('epc', k), property_id=pid(k), company_id=p['company_id'], user_id=U, certificate_number=p['epc_certificate_number'], current_rating=p['epc_rating'],
        potential_rating={'C': 'B', 'D': 'B', 'E': 'C'}[p['epc_rating']], lodgement_date=p['epc_expiry_date'].replace(year=p['epc_expiry_date'].year - 10), expiry_date=p['epc_expiry_date'],
        certificate_url='https://find-energy-certificate.service.gov.uk/energy-certificate/' + p['epc_certificate_number'], matched_by='address', fetched_at=dt.datetime(2026, 9, 6, 5, 30)) for k, p in P.items()])

# ── Tenancies ───────────────────────────────────────────────────────────────
section('tenancies')
T = []
def ten(key, prop_key, name, start, rent, due=1, status='rented', end=None, source='tenant', **kw):
    row = dict(id=uid('ten', key), property_id=pid(prop_key), company_id=C1, user_id=U, tenant_name=name, tenancy_start=start, tenancy_end=end, rent_amount=rent, rent_frequency='monthly', rent_due_day=due, payment_window_days=5, status=status, payment_source=source, confirmed_at=dt.datetime(2026, 1, 5, 10, 0), confirmed_by=U, created_by=U, needs_confirmation=False)
    row.update(kw); T.append(row); return row
ten('p1',  1,  'Claire Robson',       dt.date(2024, 3, 1),   725, 1)
ten('p2',  2,  'Daniel & Priya Mehta', dt.date(2025, 6, 14), 850, 14)
ten('p3',  3,  'Tom Ashby',           dt.date(2023, 11, 1),  695, 1, opening_arrears=0)
ten('p4',  4,  'Gemma Lawson',        dt.date(2022, 8, 15),  795, 15, status='notice_given', notice_received_date=dt.date(2026, 8, 20), expected_move_out=dt.date(2026, 10, 19))
ten('p5x', 5,  'Jordan Price',        dt.date(2023, 4, 1),   650, 1, status='ended', end=dt.date(2026, 8, 14))
ten('p6',  6,  'Aisha Khan',          dt.date(2024, 9, 1),   550, 1)
ten('p7',  7,  'Ryan Cole',           dt.date(2025, 2, 1),   575, 1)
ten('p8',  8,  'Margaret Ellis',      dt.date(2023, 5, 1),   550, 1, source='universal_credit', benefit_type='Universal Credit housing element', benefit_contribution=550, tenant_contribution=0, benefit_frequency='monthly', benefit_next_payment_date=dt.date(2026, 10, 3), benefit_paid_to='landlord')
ten('p9x', 9,  'Nathan Reid',         dt.date(2024, 2, 1),   525, 1, status='ended', end=dt.date(2026, 7, 31))
ten('p10x',10, 'Hannah Moore',        dt.date(2024, 1, 15),  560, 1, status='ended', end=dt.date(2026, 3, 15))
ten('p10', 10, 'Lewis & Beth Turner', dt.date(2026, 4, 1),   595, 1)
ten('p11', 11, 'Sophie Grant',        dt.date(2025, 11, 15), 565, 1)
ten('p12', 12, 'HMO, 5 rooms',        dt.date(2024, 3, 1),   2150, 1)
insert('tenancies', T, cols=sorted({c for t in T for c in t}))

def det(prop_key, names, email, phone, start, end, dep, scheme, ref, review, brk='Six-month break clause, two months notice'):
    return dict(id=uid('td', prop_key), property_id=pid(prop_key), user_id=U, tenant_names=names, tenant_email=email, tenant_phone=phone, tenancy_start=start, tenancy_end=end, deposit_amount=dep, deposit_scheme=scheme, deposit_ref=ref, rent_review_date=review, break_clause=brk, notice_period='2 months')
DPS, TDS, MYD = 'DPS - Deposit Protection Service', 'TDS - Tenancy Deposit Scheme', 'mydeposits'
TD = [
  det(1,  'Claire Robson',        'claire.robson@example.com', '07700 900101', dt.date(2024, 3, 1),   None, 836,  DPS, 'DPS-4471-0932', dt.date(2027, 3, 1)),
  det(2,  'Daniel & Priya Mehta', 'd.mehta@example.com',       '07700 900102', dt.date(2025, 6, 14),  None, 980,  TDS, 'TDS-88213-A',   dt.date(2026, 6, 14)),
  det(3,  'Tom Ashby',            'tom.ashby@example.com',     '07700 900103', dt.date(2023, 11, 1),  None, 801,  DPS, 'DPS-3320-1187', dt.date(2026, 11, 1)),
  det(4,  'Gemma Lawson',         'gemma.lawson@example.com',  '07700 900104', dt.date(2022, 8, 15),  dt.date(2026, 10, 19), 917, MYD, 'MYD-2022-55190', dt.date(2026, 8, 15)),
  det(6,  'Aisha Khan',           'aisha.khan@example.com',    '07700 900106', dt.date(2024, 9, 1),   None, 634,  DPS, 'DPS-5102-2231', dt.date(2026, 9, 1)),
  det(7,  'Ryan Cole',            'ryan.cole@example.com',     '07700 900107', dt.date(2025, 2, 1),   None, 663,  DPS, 'DPS-5102-2232', dt.date(2027, 2, 1)),
  det(8,  'Margaret Ellis',       'm.ellis@example.com',       '07700 900108', dt.date(2023, 5, 1),   None, 634,  TDS, 'TDS-71004-C',   dt.date(2027, 5, 1)),
  det(10, 'Lewis & Beth Turner',  'turners@example.com',       '07700 900110', dt.date(2026, 4, 1),   dt.date(2027, 3, 31), 686, DPS, 'DPS-5102-2235', dt.date(2027, 4, 1)),
  det(11, 'Sophie Grant',         'sophie.grant@example.com',  '07700 900111', dt.date(2025, 11, 15), None, 651,  DPS, 'DPS-5102-2236', dt.date(2026, 11, 15)),
  det(12, 'Room-by-room (5 tenants)', 'brunswick@example.com', '07700 900112', dt.date(2024, 3, 1),  None, 2480, TDS, 'TDS-90211-H',   dt.date(2027, 3, 1), brk='Rolling room tenancies'),
]
insert('tenancy_details', TD)
insert('deposit_protection', [dict(id=uid('dep', d['property_id']), property_id=d['property_id'], user_id=U, tenant_name=d['tenant_names'], amount=d['deposit_amount'], scheme=d['deposit_scheme'].split(' - ')[0], reference=d['deposit_ref'], registered_date=d['tenancy_start'] + dt.timedelta(days=9), prescribed_info_sent='Yes') for d in TD])
rtr_docs = {1: ('Passport', None), 2: ('Online Share Code', dt.date(2027, 6, 30)), 3: ('Passport', None), 4: ('Passport', None), 6: ('BRP', dt.date(2027, 2, 28)), 7: ('Passport', None), 8: ('Passport', None), 10: ('Passport', None), 11: ('Online Share Code', dt.date(2026, 11, 30)), 12: ('Passport', None)}
insert('right_to_rent', [dict(id=uid('rtr', k), property_id=pid(k), user_id=U, tenant_name=[d for d in TD if d['property_id'] == pid(k)][0]['tenant_names'], doc_type=doc, doc_reference=f'RTR-{k:02d}-{2026 - k}', check_date=[d for d in TD if d['property_id'] == pid(k)][0]['tenancy_start'] - dt.timedelta(days=3), expiry_date=exp, follow_up_date=(exp - dt.timedelta(days=28)) if exp else None) for k, (doc, exp) in rtr_docs.items()])

insert('hmo_rooms', [dict(id=uid('room', n), property_id=pid(12), company_id=C1, user_id=U, room_name=f'Room {n}', rent_pcm=430, tenant_name=nm, tenancy_start=st, status='occupied') for n, (nm, st) in enumerate([('Jake Milburn', dt.date(2025, 2, 1)), ('Olivia Frost', dt.date(2025, 9, 1)), ('Connor Bell', dt.date(2024, 6, 1)), ('Amelia Shaw', dt.date(2026, 1, 10)), ('Noah Hussain', dt.date(2025, 11, 1))], start=1)])
insert('hmo_licences', [dict(id=uid('hmolic', 12), property_id=pid(12), company_id=C1, user_id=U, licence_type='mandatory', authority='Sunderland City Council', licence_number='HMO/2024/0187', issued_date=dt.date(2024, 2, 1), expiry_date=dt.date(2029, 1, 31), status='active')])

# ── Rent payments (residential) ─────────────────────────────────────────────
section('rent_payments (residential)')
def months(a, b):
    y, m = a.year, a.month
    while (y, m) <= (b.year, b.month):
        yield y, m
        m += 1
        if m == 13: y, m = y + 1, 1
def last_day(y, m): return (dt.date(y + (m == 12), (m % 12) + 1, 1) - dt.timedelta(days=1)).day
# One row per tenancy-month from Jan 2025 to the current month, expanded in
# SQL so the seed stays small. Overrides below turn a few months into the
# late / missed / part-paid cases the screenshots need.
out.append(f"""insert into public.rent_payments (property_id, user_id, tenancy_id, year, month, month_label, status, amount, expected_amount, due_date)
select t.property_id, t.user_id, t.id, extract(year from d)::int, extract(month from d)::int, to_char(d, 'Mon YYYY'), 'paid', t.rent_amount, t.rent_amount,
       least(d::date + (t.rent_due_day - 1), (d + interval '1 month - 1 day')::date)
from public.tenancies t
cross join lateral generate_series(greatest(date_trunc('month', t.tenancy_start), date '2025-01-01'), least(coalesce(t.tenancy_end, date '2026-09-07'), date '2026-09-07'), interval '1 month') d
where t.user_id = {q(U)};""")
def ovr(pk, y, m, status, amount, note=None):
    out.append(f"update public.rent_payments set status = {q(status)}, amount = {q(amount)}, notes = {q(note)} where property_id = {q(pid(pk))} and year = {y} and month = {m};")
ovr(3, 2026, 3, 'late', 695, 'Paid 9 days late')
ovr(3, 2026, 7, 'overdue', 0); ovr(3, 2026, 8, 'overdue', 0); ovr(3, 2026, 9, 'partial', 300, 'Part payment received 5 Sept')
ovr(7, 2026, 9, 'partial', 300, 'Tenant paid £300, balance promised 12 Sept')
ovr(2, 2025, 10, 'late', 850, 'Paid 6 days late')
insert('rent_payments', [dict(id=uid('rp', pk, y0, m0), property_id=pid(pk), user_id=U, year=y0, month=m0, month_label=dt.date(y0, m0, 1).strftime('%b %Y'), status=st, amount=0, expected_amount=0)
                         for pk, (y0, m0), st in [(5, (2026, 9), 'void'), (9, (2026, 8), 'refurb'), (9, (2026, 9), 'refurb')]],
       cols=['id', 'property_id', 'user_id', 'year', 'month', 'month_label', 'status', 'amount', 'expected_amount'])
insert('rent_history', [dict(id=uid('rh', 1), property_id=pid(1), user_id=U, change_type='increase', effective_date=dt.date(2026, 3, 1), previous_rent=675, new_rent=725, next_review_date=dt.date(2027, 3, 1), notice_served='Section 13 served 20 Dec 2025')])

# ── Short-term lets: Hostaway connection, manager, bookings ─────────────────
section('short-term lets')
insert('hostaway_connections', [dict(id=HC, user_id=U, company_id=C2, account_id='demo-91004', status='active', last_synced_at=dt.datetime(2026, 9, 7, 12, 10), last_sync_status='ok', token_expires_at=dt.datetime(2028, 9, 1))])
insert('hostaway_property_mappings', [dict(id=uid('map', r), connection_id=HC, user_id=U, hostaway_listing_id=900000 + r, hostaway_listing_name=f'Quayside Loft {r}', property_id=pid(20 + r)) for r in range(1, 7)])
# Bookings are generated in SQL: a deterministic random walk per room from
# 1 March to mid December 2026 (stay 1-5 nights, gap 0-5 nights), priced by
# room and season, split Booking.com / Airbnb / Direct. Cancelled bookings
# earn nothing and get no Rent Tracker segment.
out.append(f"""with recursive params as (
  select r, ('de3d0001-0000-4000-8000-0000000000' || (20 + r))::uuid as pid, 900000 + r as listing, (array[89, 95, 82, 110, 118, 99])[r] as base
  from generate_series(1, 6) r
), walk(r, n, arrival, nights) as (
  select r, 1, date '2026-03-01' + (abs(hashtext('start' || r)) % 4),
         (select case when h < 10 then 1 when h < 45 then 2 when h < 75 then 3 when h < 90 then 4 else 5 end from (select abs(hashtext('n' || r || ':1')) % 100 h) x)
  from params
  union all
  select r, n + 1,
         arrival + nights + (select case when h < 40 then 0 when h < 70 then 1 when h < 85 then 2 when h < 95 then 3 else 5 end from (select abs(hashtext('g' || r || ':' || n)) % 100 h) x),
         (select case when h < 10 then 1 when h < 45 then 2 when h < 75 then 3 when h < 90 then 4 else 5 end from (select abs(hashtext('n' || r || ':' || (n + 1))) % 100 h) x)
  from walk where arrival < date '2026-12-01'
), priced as (
  select w.r, w.n, w.arrival, w.nights, w.arrival + w.nights as departure, p.pid, p.listing,
         round(p.base * (case extract(month from w.arrival) when 3 then 0.85 when 4 then 0.9 when 5 then 1.0 when 6 then 1.05 when 7 then 1.2 when 8 then 1.25 when 9 then 1.05 when 10 then 0.95 when 11 then 0.85 else 0.9 end)
               * (0.93 + (abs(hashtext('rate' || w.r || ':' || w.n)) % 16) / 100.0)) as rate,
         case when abs(hashtext('ch' || w.r || ':' || w.n)) % 100 < 45 then 'Booking.com' when abs(hashtext('ch' || w.r || ':' || w.n)) % 100 < 85 then 'Airbnb' else 'Direct' end as channel,
         case when abs(hashtext('st' || w.r || ':' || w.n)) % 100 < 90 then 'new' when abs(hashtext('st' || w.r || ':' || w.n)) % 100 < 96 then 'modified' else 'cancelled' end as status,
         (array['A. Patel','M. O''Connor','S. Lindqvist','J. Okafor','R. Hughes','E. Novak','L. Fernandes','K. Tanaka','D. Murphy','H. Schmidt','C. Baptiste','N. Rahman','P. Kowalski','T. Nguyen','B. Sorensen','G. Rossi','F. Dubois','W. Chen','I. Petrova','O. Adeyemi','V. Costa','Y. Haddad','Z. Mahmood','Q. Lee'])[1 + abs(hashtext('gu' || w.r || ':' || w.n)) % 24] as guest,
         91000000 + w.r * 1000 + w.n as res_id,
         3 + abs(hashtext('lead' || w.r || ':' || w.n)) % 38 as lead_days
  from walk w join params p using (r)
), fin as (
  select *, nights * rate as accom, nights * rate + 25 as total,
         case channel when 'Airbnb' then round(nights * rate * 0.153, 2) when 'Booking.com' then round((nights * rate + 25) * 0.15, 2) else 0 end as comm,
         arrival <= current_date as paid
  from priced
)
insert into public.stl_bookings (user_id, property_id, provider, hostaway_connection_id, hostaway_reservation_id, hostaway_listing_id, source, status, guest_name, arrival, departure, currency,
                                 total_amount, amount_paid, amount_due, channel_commission, hostaway_commission, cleaning_fee, tax_amount, payment_status, fee_lines, synced_at, financials_synced_at, created_at)
select {q(U)}, pid, 'hostaway', {q(HC)}, res_id, listing, channel, status, guest, arrival, departure, 'GBP',
       total, case when paid and status <> 'cancelled' then total else 0 end, case when paid or status = 'cancelled' then 0 else total end, comm, 0, 25, 0,
       case when paid then 'Paid' else 'Unpaid' end, jsonb_build_object('finance', jsonb_build_object('cleaningFee', 25, 'paymentStatus', case when paid then 'Paid' else 'Unpaid' end)),
       timestamptz '2026-09-07 12:10:00+00', timestamptz '2026-09-07 12:10:00+00', (arrival - lead_days)::timestamptz + interval '9 hours'
from fin;""")
# Rent Tracker segment per revenue booking, in the sync's format, then link it.
out.append(f"""insert into public.rent_payments (property_id, user_id, year, month, month_label, status, amount, period_start, period_end, notes)
select property_id, user_id, extract(year from arrival)::int, extract(month from arrival)::int, to_char(arrival, 'Mon YYYY'), 'paid', total_amount, arrival, departure - 1,
       'STL · ' || source || ' · ' || guest_name || ' · ' || arrival || ' → ' || departure || ' · Hostaway #' || hostaway_reservation_id
from public.stl_bookings where user_id = {q(U)} and status <> 'cancelled';""")
out.append(f"""update public.stl_bookings b set rent_payment_id = rp.id
from public.rent_payments rp
where b.user_id = {q(U)} and rp.user_id = b.user_id and rp.property_id = b.property_id and rp.period_start = b.arrival and rp.notes like 'STL · %' and b.status <> 'cancelled';""")
insert('stl_adjustments', [dict(id=uid('adj', 1), booking_id=None, property_id=pid(23), company_id=C2, user_id=U, adjustment_date=dt.date(2026, 8, 20), amount=-85, kind='refund', channel='Booking.com', reference='BDC-4410-R', notes='Goodwill refund, late check-in after a lock fault', created_by=U)])

# ── Compliance items ────────────────────────────────────────────────────────
section('compliance_items')
CI = []
def cert(pk, ctype, name, issue, expiry=None):
    CI.append(dict(id=uid('cert', pk, ctype, issue), property_id=pid(pk), user_id=U, cert_type=ctype, cert_name=name, issue_date=issue, expiry_date=expiry, reminder_days=30))
def yrs(d, n): return d.replace(year=d.year + n)
gas_expiry = {1: dt.date(2026, 8, 26), 2: dt.date(2026, 9, 27), 3: dt.date(2027, 4, 2), 4: dt.date(2027, 1, 19), 6: dt.date(2027, 5, 11), 7: dt.date(2027, 5, 11), 8: dt.date(2027, 5, 11), 10: dt.date(2027, 5, 11), 11: dt.date(2027, 5, 11), 12: dt.date(2027, 2, 8), 9: dt.date(2027, 5, 11), 13: None}
for pk, exp in gas_expiry.items():
    if exp: cert(pk, 'gas_safety', 'Gas Safety Certificate (CP12)', exp - dt.timedelta(days=364), exp)
for pk, exp in {1: dt.date(2029, 6, 30), 2: dt.date(2030, 3, 15), 4: dt.date(2028, 11, 2), 5: dt.date(2029, 2, 20), 6: dt.date(2028, 6, 1), 7: dt.date(2028, 6, 1), 8: dt.date(2028, 6, 1), 9: dt.date(2028, 6, 1), 10: dt.date(2028, 6, 1), 11: dt.date(2028, 6, 1), 12: dt.date(2029, 1, 31), 21: dt.date(2029, 7, 1), 22: dt.date(2029, 7, 1), 23: dt.date(2029, 7, 1), 24: dt.date(2029, 7, 1), 25: dt.date(2029, 7, 1), 26: dt.date(2029, 7, 1)}.items():
    cert(pk, 'eicr', 'Electrical Installation Condition Report', yrs(exp, -5), exp)
let_keys = [1, 2, 3, 4, 6, 7, 8, 10, 11, 12]
for pk in let_keys:
    ts = [t for t in T if t['property_id'] == pid(pk) and t['status'] in ('rented', 'notice_given')][0]['tenancy_start']
    chk = dt.date(2026, 2, 3) if pk != 4 else dt.date(2025, 9, 9)
    cert(pk, 'smoke_alarm', 'Smoke alarm test', chk, yrs(chk, 1))
    if P[pk]['has_gas_supply']: cert(pk, 'co_alarm', 'Carbon monoxide alarm test', chk, yrs(chk, 1))
    cert(pk, 'tenancy_agreement', 'Assured shorthold tenancy agreement', ts)
    cert(pk, 'deposit_protection', 'Deposit certificate and prescribed information', ts + dt.timedelta(days=9))
    cert(pk, 'right_to_rent', 'Right to Rent check', ts - dt.timedelta(days=3))
    if pk != 3: cert(pk, 'rra_info_sheet', 'Renters Rights information sheet', max(ts, dt.date(2026, 6, 1)))
    if pk != 2: cert(pk, 'legionella', 'Legionella risk assessment', dt.date(2025, 3, 12), dt.date(2027, 3, 11))
    cert(pk, 'inventory', 'Inventory and check-in report', ts)
    if pk in (1, 2, 4, 12): cert(pk, 'boiler_service', 'Annual boiler service', dt.date(2026, 6, 3) if pk != 4 else dt.date(2025, 10, 1), dt.date(2027, 6, 2) if pk != 4 else dt.date(2026, 9, 30))
cert(12, 'hmo', 'Mandatory HMO licence, Sunderland City Council', dt.date(2024, 2, 1), dt.date(2029, 1, 31))
cert(12, 'fire', 'Fire risk assessment', dt.date(2026, 1, 16), dt.date(2027, 1, 15))
cert(12, 'fire_alarm_service', 'Fire alarm service (BS 5839)', dt.date(2026, 5, 20), dt.date(2026, 11, 19))
cert(12, 'emergency_lighting', 'Emergency lighting certificate', dt.date(2026, 3, 2), dt.date(2027, 3, 1))
cert(12, 'pat', 'PAT testing', dt.date(2026, 2, 11), dt.date(2027, 2, 10))
for r in range(21, 27):
    cert(r, 'smoke_alarm', 'Smoke alarm test', dt.date(2026, 7, 1), dt.date(2027, 6, 30))
    cert(r, 'pat', 'PAT testing', dt.date(2026, 7, 1), dt.date(2027, 6, 30))
    cert(r, 'legionella', 'Legionella risk assessment', dt.date(2025, 7, 1), dt.date(2027, 6, 30))
insert('compliance_items', CI)

# ── Insurance ───────────────────────────────────────────────────────────────
section('insurance')
POL = [
  (uid('pol', 1), C1, 'Northgate portfolio, landlord buildings', 'Aviva', 'Sunderland Insurance Brokers', 'AV-LL-2025-118842', dt.date(2025, 11, 1), dt.date(2026, 10, 31), 2940, [1, 2, 3, 4, 5, 12, 13]),
  (uid('pol', 2), C1, 'Elmfield House, block policy', 'Zurich', 'Sunderland Insurance Brokers', 'ZU-BLK-77120', dt.date(2026, 4, 1), dt.date(2027, 3, 31), 1860, [6, 7, 8, 9, 10, 11]),
  (uid('pol', 3), C2, 'Quayside Lofts, serviced accommodation', 'Towergate', None, 'TG-SA-2026-0419', dt.date(2026, 1, 15), dt.date(2027, 1, 14), 2210, [21, 22, 23, 24, 25, 26]),
]
insert('insurance_policies', [dict(id=i, company_id=c, user_id=U, policy_type='landlord', policy_name=n, provider=pr, broker=br, policy_number=pn, start_date=s, expiry_date=e, premium=prem, payment_freq='annual', reminder_days=30) for i, c, n, pr, br, pn, s, e, prem, _ in POL])
insert('insurance_policy_properties', [dict(policy_id=i, property_id=pid(k)) for i, *_, keys in POL for k in keys])

# ── Refurbs ─────────────────────────────────────────────────────────────────
section('refurbs')
R1, R2, R3 = uid('refurb', 9), uid('refurb', 13), uid('refurb', 3)
insert('refurb_projects', [
  dict(id=R1, property_id=pid(9),  company_id=C1, user_id=U, title='Full refurbishment', stage='in_progress', agreed_price=8500,  contractor_name='Wearside Build & Fix', start_date=dt.date(2026, 8, 18), target_end_date=dt.date(2026, 9, 26), funding='cash',   expected_rent_after=595, expected_value_after=78000,  treatment='capital', notes='Kitchen, bathroom, rewire check, full redecoration.'),
  dict(id=R2, property_id=pid(13), company_id=C1, user_id=U, title='Refurbishment before first let', stage='in_progress', agreed_price=24000, contractor_name='Durham Property Renovations', start_date=dt.date(2026, 8, 11), target_end_date=dt.date(2026, 10, 30), funding='bridge', expected_rent_after=895, expected_value_after=165000, treatment='capital', notes='New kitchen, bathroom, boiler, windows to rear, decoration throughout.'),
  dict(id=R3, property_id=pid(3),  company_id=C1, user_id=U, title='Bathroom refit', stage='complete', agreed_price=3200, contractor_name='Wearside Build & Fix', start_date=dt.date(2026, 4, 28), target_end_date=dt.date(2026, 5, 12), completed_date=dt.date(2026, 5, 12), funding='cash', treatment='revenue'),
])
insert('refurb_lines', [
  dict(id=uid('rl', 1), project_id=R1, kind='payment', amount=4250, date=dt.date(2026, 8, 18), payee='Wearside Build & Fix', description='50% on start', created_by=U),
  dict(id=uid('rl', 2), project_id=R1, kind='extra',   amount=600,  date=dt.date(2026, 8, 29), payee='Wearside Build & Fix', description='Replace consumer unit, found on strip-out', created_by=U),
  dict(id=uid('rl', 3), project_id=R2, kind='payment', amount=12000, date=dt.date(2026, 8, 11), payee='Durham Property Renovations', description='Stage 1, on start', created_by=U),
  dict(id=uid('rl', 4), project_id=R2, kind='payment', amount=6000,  date=dt.date(2026, 9, 1),  payee='Durham Property Renovations', description='Stage 2, first fix complete', created_by=U),
  dict(id=uid('rl', 5), project_id=R2, kind='extra',   amount=1150,  date=dt.date(2026, 8, 25), payee='Durham Property Renovations', description='Damp-proof course to rear wall', created_by=U),
  dict(id=uid('rl', 6), project_id=R3, kind='payment', amount=3200,  date=dt.date(2026, 5, 12), payee='Wearside Build & Fix', description='Paid on completion', created_by=U),
])
MS = [('keys_received', 'Keys received'), ('strip_out', 'Strip out'), ('first_fix', 'First fix (electrics and plumbing)'), ('second_fix', 'Second fix'), ('decoration', 'Decoration and flooring'), ('certificates', 'Gas and electrical certificates'), ('snagging', 'Snagging signed off'), ('ready_to_let', 'Ready to let')]
def ms(project, done_upto, dates):
    return [dict(id=uid('rm', project, k), project_id=project, milestone_key=k, label=l, sort_order=i, is_enabled=True, completed=i < done_upto, completed_date=dates[i] if i < done_upto else None) for i, (k, l) in enumerate(MS)]
insert('refurb_milestones', ms(R1, 3, [dt.date(2026, 8, 18), dt.date(2026, 8, 21), dt.date(2026, 8, 30)]) + ms(R2, 3, [dt.date(2026, 8, 11), dt.date(2026, 8, 15), dt.date(2026, 8, 30)]) + ms(R3, 8, [dt.date(2026, 4, 28), dt.date(2026, 4, 29), dt.date(2026, 5, 2), dt.date(2026, 5, 6), dt.date(2026, 5, 9), dt.date(2026, 5, 11), dt.date(2026, 5, 12), dt.date(2026, 5, 12)]))

# ── Deals ───────────────────────────────────────────────────────────────────
section('deals')
def deal(key, **kw):
    base = dict(id=uid('deal', key), user_id=U, company_id=C1, deal_type='btl', purchase_type='mortgage', is_auction=False, is_additional_property=True, is_first_time_buyer=False, legal_fees=1300, survey_cost=450, auction_fees=0, broker_fee=495, other_costs=0, deposit_percent=25, mortgage_rate=5.1, mortgage_term=25, mortgage_type='interest_only', mortgage_fee_percent=1, void_percent=4, agent_fee_percent=0, maintenance_percent=6, insurance_monthly=28, service_charge_monthly=0, ground_rent_monthly=0, ownership_type='company', section24_rate=0, rent_growth_percent=3, capital_growth_percent=3, agent_fee_vat='ex_vat', hmo_rent_mode='same', hmo_room_rents=[])
    base.update(kw); return base
D = [
  deal('d1', name='16 Beechwood Grove', address='16 Beechwood Grove, Sunderland, SR3 1XE', status='analysing', purchase_price=92000, monthly_rent=725, refurb_cost=4500, notes='Ex-council semi, sitting tenant leaving in October. Agent says vendor will take 90k.'),
  deal('d2', name='Flat 2, Harbour View', address='Flat 2, Harbour View, Roker, Sunderland, SR6 9NB', status='offer_made', purchase_price=78500, monthly_rent=650, refurb_cost=1500, service_charge_monthly=95, ground_rent_monthly=12.5, notes='Leasehold, 112 years left. Offer of 76,000 in on 3 Sept.'),
  deal('d3', name='5 Coronation Street', address='5 Coronation Street, Hetton-le-Hole, DH5 9AB', status='under_offer', deal_type='brrr', purchase_type='cash', purchase_price=71000, monthly_rent=725, refurb_cost=18500, brrr_end_value=115000, brrr_refinance_ltv=75, brrr_new_rate=5.3, brrr_new_term=25, target_completion_date=dt.date(2026, 10, 24), refurb_start_date=dt.date(2026, 10, 26), refurb_end_date=dt.date(2026, 12, 12), notes='Probate sale, needs full refurb. Refinance at 75% should return most of the cash.'),
  deal('d4', name='112 Chester Road', address='112 Chester Road, Sunderland, SR4 7HG', status='exchanged', deal_type='hmo', purchase_price=165000, hmo_rooms=5, hmo_rent_per_room=475, monthly_rent=2375, refurb_cost=12000, hmo_utilities_monthly=380, hmo_council_tax_monthly=190, hmo_licence_annual=320, exchanged_date=dt.date(2026, 8, 29), expected_completion_date=dt.date(2026, 9, 26), target_completion_date=dt.date(2026, 9, 26), notes='Licensed 5-bed HMO, three rooms currently let. Completion 26 Sept.'),
]
insert('deals', D, cols=sorted({c for d in D for c in d}))
DM = [('offer_submitted', 'offer', 'Offer submitted'), ('offer_accepted', 'offer', 'Offer accepted (verbal)'), ('memorandum_received', 'offer', 'Memorandum of sale received'), ('solicitor_instructed', 'professionals', 'Solicitor instructed'), ('broker_instructed', 'professionals', 'Mortgage broker instructed'), ('mortgage_applied', 'professionals', 'Mortgage application submitted'), ('survey_instructed', 'professionals', 'Survey instructed'), ('searches_ordered', 'legal', 'Searches ordered'), ('contract_pack_received', 'legal', 'Contract pack received'), ('survey_completed', 'legal', 'Survey completed'), ('searches_received', 'legal', 'Searches received'), ('enquiries_raised', 'legal', 'Enquiries raised by solicitor'), ('mortgage_offer', 'legal', 'Mortgage offer received'), ('enquiries_satisfied', 'legal', 'Enquiries satisfied'), ('insurance_arranged', 'exchange', 'Buildings insurance arranged'), ('deposit_paid', 'exchange', 'Deposit paid to solicitor'), ('contracts_exchanged', 'exchange', 'Contracts exchanged'), ('completion_date_set', 'exchange', 'Completion date confirmed'), ('funds_transferred', 'completion', 'Completion funds transferred'), ('keys_received', 'completion', 'Keys received'), ('sdlt_filed', 'completion', 'SDLT filed with HMRC (14 day deadline)'), ('utilities_transferred', 'completion', 'Utilities transferred'), ('title_registered', 'completion', 'Title registered at Land Registry')]
def dms(deal_id, done, base_date):
    return [dict(id=uid('dm', deal_id, k), deal_id=deal_id, milestone_key=k, label=l, stage=s, sort_order=i, is_enabled=True, is_required=s in ('offer', 'legal', 'exchange'), completed=i < done, completed_date=(base_date + dt.timedelta(days=i * 4)) if i < done else None) for i, (k, s, l) in enumerate(DM)]
insert('deal_milestones', dms(D[3]['id'], 18, dt.date(2026, 6, 20)) + dms(D[2]['id'], 7, dt.date(2026, 8, 12)) + dms(D[1]['id'], 1, dt.date(2026, 9, 3)))

# ── Maintenance, contractors, expenses ──────────────────────────────────────
section('maintenance and expenses')
insert('contractors', [
  dict(id=uid('con', 1), user_id=U, company_id=C1, name='Wearside Build & Fix', trade='Builder', phone='0191 496 0101', email='jobs@wearsidebuild.example', preferred=True),
  dict(id=uid('con', 2), user_id=U, company_id=C1, name='Sparks NE', trade='Electrician', phone='0191 496 0102', email='hello@sparksne.example', preferred=True),
  dict(id=uid('con', 3), user_id=U, company_id=C1, name='Gas Safe North East', trade='Gas engineer', phone='0191 496 0103', email='book@gsne.example', preferred=True),
])
insert('maintenance_jobs', [
  dict(id=uid('mj', 1), property_id=pid(2), user_id=U, title='Boiler losing pressure, no hot water in the morning', description='Tenant reports the boiler drops to 0.5 bar overnight and needs topping up daily. Pressure gauge photo attached.', category='plumbing', priority='high', status='open', date_raised=dt.date(2026, 9, 4), reported_by_tenant=True, photos=[], ai_severity='high', ai_triaged_at=dt.datetime(2026, 9, 4, 8, 12),
       ai_triage={'severity': 'high', 'trade': 'Gas Safe heating engineer', 'diagnosis': 'Daily pressure loss points to a leak on the system or a failing expansion vessel rather than user error. Not an immediate safety risk but the tenant is without reliable hot water.', 'urgency': 'Attend within 48 hours', 'estimated_cost': '£120 to £280', 'questions_for_tenant': ['Any damp patches under radiators or the boiler?', 'Does the pressure drop faster when heating is on?']}),
  dict(id=uid('mj', 2), property_id=pid(7), user_id=U, title='Bathroom extractor fan not working', description='Fan stopped, condensation building up on the window.', category='electrical', priority='medium', status='in-progress', contractor='Sparks NE', contractor_phone='0191 496 0102', quoted_cost=120, date_raised=dt.date(2026, 8, 28), reported_by_tenant=True, photos=[]),
  dict(id=uid('mj', 3), property_id=pid(1), user_id=U, title='Fence panel blown down', description='Rear garden, one panel and post.', category='other', priority='low', status='complete', contractor='Wearside Build & Fix', actual_cost=85, date_raised=dt.date(2026, 7, 14), date_resolved=dt.date(2026, 7, 19), reported_by_tenant=False, photos=[]),
  dict(id=uid('mj', 4), property_id=pid(12), user_id=U, title='Communal hallway light flickering', description='First floor landing.', category='electrical', priority='medium', status='open', date_raised=dt.date(2026, 9, 6), reported_by_tenant=True, photos=[]),
])
EX = [
  dict(property_id=pid(1), category='repairs', description='Fence panel and post replaced', amount=85, date=dt.date(2026, 7, 19)),
  dict(property_id=pid(2), category='repairs', description='Annual boiler service', amount=140, date=dt.date(2026, 6, 3)),
  dict(property_id=pid(5), category='ground_rent', description='Ground rent 2026', amount=150, date=dt.date(2026, 1, 1)),
  dict(property_id=pid(5), category='service_charge', description='Service charge, first half 2026', amount=480, date=dt.date(2026, 1, 1)),
  dict(property_id=pid(5), category='service_charge', description='Service charge, second half 2026', amount=480, date=dt.date(2026, 7, 1)),
  dict(property_id=pid(5), category='other', description='Check-out clean and inventory', amount=180, date=dt.date(2026, 8, 16)),
  dict(property_id=pid(3), category='legal', description='Arrears letter, solicitor', amount=95, date=dt.date(2026, 8, 21)),
  dict(property_id=pid(1), category='insurance', description='Buildings insurance, share of portfolio policy', amount=420, date=dt.date(2025, 11, 1)),
  dict(property_id=pid(12), category='legal', description='HMO licence renewal fee, first instalment', amount=320, date=dt.date(2026, 2, 1)),
]
for m in range(1, 10):
    EX.append(dict(property_id=pid(12), category='utilities', description='Gas, electric and broadband (bills included)', amount=380, date=dt.date(2026, m, 1), recurring=True, recurring_freq='monthly'))
    EX.append(dict(property_id=pid(6), category='utilities', description='Communal electricity, Elmfield House', amount=42, date=dt.date(2026, m, 1), recurring=True, recurring_freq='monthly'))
insert('property_expenses', [dict(id=uid('ex', i), user_id=U, recurring=False, **e) if 'recurring' not in e else dict(id=uid('ex', i), user_id=U, **e) for i, e in enumerate(EX)], cols=['id', 'property_id', 'user_id', 'category', 'description', 'amount', 'date', 'recurring', 'recurring_freq'])

# ── Autopilot, notifications, insights ──────────────────────────────────────
section('autopilot, notifications, insights')
AP = [
  ('arrears', 'high', 3, 'Rent arrears on 9 Ferndale Terrace: £1,785 (2.6 months)', 'arrears:%s:2m', {'arrears': 1785, 'rent_pcm': 695, 'property': '9 Ferndale Terrace'}, TODAY,
   'Dear Mr Ashby,\n\nOur records show rent of £695 due on 1 July and 1 August 2026 remains unpaid, and only £300 of the £695 due on 1 September has been received, leaving a balance of £1,785.\n\nPlease pay the outstanding amount within 7 days or contact us to agree a payment plan. If we do not hear from you we may have to take further action under the tenancy agreement.\n\nKind regards,\nSam Whitfield, Northgate Property Ltd'),
  ('compliance', 'high', 1, 'Gas Safety certificate expired 12 days ago at 14 Ashworth Road', 'compliance:%s:gas_safety:expired', {'cert': 'Gas Safety (CP12)', 'expired_days': 12, 'property': '14 Ashworth Road'}, TODAY,
   'Hi Claire,\n\nYour annual gas safety check is overdue. Gas Safe North East can attend on Wednesday 10 September between 9am and 12pm. Please reply to confirm someone can give access, or suggest another time this week.\n\nThanks,\nSam'),
  ('compliance', 'medium', 2, 'Gas Safety certificate expires in 20 days at 27 Hillcrest Avenue', 'compliance:%s:gas_safety:expiring', {'cert': 'Gas Safety (CP12)', 'expires_in_days': 20, 'property': '27 Hillcrest Avenue'}, TODAY + dt.timedelta(days=10),
   'Hi Daniel and Priya,\n\nThe annual gas safety check for 27 Hillcrest Avenue is due by 27 September. Could you let me know two or three half-days that suit you in the next fortnight and I will book the engineer.\n\nThanks,\nSam'),
  ('void', 'medium', 5, '3 Mariners Court has been vacant for 23 days', 'void:%s', {'vacant_days': 23, 'rent_pcm': 650, 'lost_rent': 492, 'property': '3 Mariners Court'}, TODAY + dt.timedelta(days=3),
   'Listing draft for Rightmove and Zoopla:\n\nBright two-bedroom second-floor apartment in Mariners Court, Seaham, a short walk from the seafront and marina. Modern kitchen, allocated parking, electric heating, unfurnished. £650 pcm, deposit £750, available now. No pets. EPC C.'),
  ('insurance', 'medium', None, 'Portfolio buildings insurance renews in 54 days (Aviva, £2,940)', 'insurance:%s', {'policy': 'Northgate portfolio, landlord buildings', 'expires': '2026-10-31', 'premium': 2940}, TODAY + dt.timedelta(days=24),
   'Hi,\n\nOur landlord buildings policy AV-LL-2025-118842 renews on 31 October. Please could you send renewal terms and two alternative quotes for the seven properties on the schedule. 8 Orchard Close should be added from completion of works (target 30 October).\n\nThanks,\nSam Whitfield'),
  ('arrears', 'medium', 7, 'Part payment on Flat 2, Elmfield House: £275 outstanding', 'arrears:%s:partial', {'arrears': 275, 'rent_pcm': 575, 'property': 'Flat 2, Elmfield House'}, TODAY + dt.timedelta(days=5),
   'Hi Ryan,\n\nThanks for the £300 on 3 September. Just confirming the remaining £275 for September is expected by 12 September as agreed. Let me know if anything changes.\n\nThanks,\nSam'),
  ('compliance', 'medium', 3, 'No EICR on file for 9 Ferndale Terrace', 'compliance:%s:eicr:missing', {'cert': 'EICR', 'property': '9 Ferndale Terrace'}, TODAY + dt.timedelta(days=14),
   'Hi Tom,\n\nWe need to carry out an electrical inspection (EICR) at the property. Sparks NE can attend Tuesday 16 September, it takes around three hours. Please confirm access.\n\nThanks,\nSam'),
]
insert('autopilot_actions', [dict(id=uid('ap', i), company_id=C1, user_id=U, property_id=pid(pk) if pk else None, kind=k, severity=sev, title=title, draft_body=body, due_date=due, status='open', dedupe_key=(dk % (pid(pk) if pk else C1)), metadata=meta, created_at=dt.datetime(2026, 9, 7, 7, 31)) for i, (k, sev, pk, title, dk, meta, due, body) in enumerate(AP)])
insert('notifications', [
  dict(id=uid('nt', 1), user_id=U, type='compliance_expired', title='Gas Safety certificate expired: 14 Ashworth Road', body='Expired 26 August 2026. Book a Gas Safe engineer and log the new certificate.', link='#/compliance', dedupe_key='compliance_expired:%s:gas_safety' % pid(1), created_at=dt.datetime(2026, 8, 27, 6, 5), metadata={'property_id': pid(1), 'cert_type': 'gas_safety'}),
  dict(id=uid('nt', 2), user_id=U, type='autopilot', title='Autopilot: 7 actions drafted for Northgate Property Ltd', body='2 high priority: rent arrears at 9 Ferndale Terrace and an expired gas certificate at 14 Ashworth Road.', link='#/autopilot', dedupe_key='autopilot:digest:%s' % C1, created_at=dt.datetime(2026, 9, 7, 7, 31), metadata={'company_id': C1, 'action_count': 7, 'high_count': 2}),
  dict(id=uid('nt', 3), user_id=U, type='compliance_expiring', title='Gas Safety certificate expires in 20 days: 27 Hillcrest Avenue', body='Due 27 September 2026.', link='#/compliance', dedupe_key='compliance_expiring:%s:gas_safety' % pid(2), created_at=dt.datetime(2026, 9, 7, 6, 5), metadata={'property_id': pid(2)}),
  dict(id=uid('nt', 4), user_id=U, type='backup', title='Weekly backup ready', body='Your account export for the week to 6 September is ready to download from Settings.', link='#/settings/backups', dedupe_key='backup:2026-W36', created_at=dt.datetime(2026, 9, 6, 3, 0), metadata={}),
])
stats = {'property_count': 19, 'total_value': 1949000, 'total_mortgage': 1131100, 'total_equity': 817900, 'ltv_percent': 58, 'monthly_rent': 8050, 'annual_rent': 96600, 'gross_yield_percent': 7.0, 'occupancy_percent': 89, 'total_arrears': 2060}
insights = [
  {'title': '9 Ferndale Terrace: £1,785 arrears, 2.6 months', 'category': 'arrears', 'severity': 'critical', 'body': 'Tom Ashby has missed July and August in full and paid £300 of September. At £695 a month this is the largest single balance in the portfolio and it is growing. Send the formal arrears letter drafted in Autopilot today and offer a payment plan; if nothing is agreed within 14 days take advice on possession grounds under the Renters Rights Act.', 'action_label': 'Open arrears letter', 'action_link': '#/autopilot'},
  {'title': 'Two mortgage products end within four months', 'category': 'expenses', 'severity': 'warning', 'body': '9 Ferndale Terrace (3.29%, ends 31 Oct) and 14 Ashworth Road (4.89%, ends 1 Dec) revert to variable rates of roughly 8.5% if nothing is done, adding about £430 a month across the two. Combined balance £136,500 at 52% LTV, so a broker should have good options. Start now: offers take 4 to 6 weeks.', 'action_label': 'Review mortgages', 'action_link': '#/properties'},
  {'title': 'Elmfield House Flat 4: refurb on track, £4,250 to pay', 'category': 'opportunity', 'severity': 'opportunity', 'body': 'First fix signed off on 30 August with two of three stage payments to come. Re-letting at £595 (up from £525) adds £840 a year and lifts the block to full occupancy. Instruct the EICR and gas certificate for the week of 22 September so the flat can be advertised the day the decorators finish.', 'action_label': 'Open refurb', 'action_link': '#/refurbs'},
  {'title': 'Quayside Lofts: August RevPAR £81, up 18% on July', 'category': 'yield', 'severity': 'info', 'body': 'The six serviced rooms ran at 78% occupancy in August at an average nightly rate of £104. Booking.com is 45% of nights but its 15% commission makes Airbnb and direct bookings worth £14 a night more. Push repeat guests to the direct booking page with a 10% code.', 'action_label': 'Open STL income', 'action_link': '#/stl'},
]
insert('portfolio_insights', [dict(id=uid('pi', 1), user_id=U, company_id=None, insights=insights, stats=stats, generated_at=dt.datetime(2026, 9, 7, 6, 45), tokens_input=8120, tokens_output=940)])

print('\n'.join(out))
