import { useTheme } from '../lib/ThemeContext'

// ── PROPERLY BRAND MARK ────────────────────────────────────────────────
// Spec: design/properly-brand/HANDOFF.md (direction 3D — endorsed lockup).
// Every variant is an outlined-path SVG generated by
// design/properly-brand/generate.js, so no brand webfonts ship to the
// client and the mark renders identically everywhere (img tags, emails
// via the PNG derivative, favicons).
//
// Variants:
//   primary   endorsed lockup (tile + wordmark + ownproperly.com) — light
//             surfaces: marketing header, PDF-adjacent chrome, decks
//   reversed  endorsed lockup for navy/dark surfaces (marketing footer)
//   short     tile + wordmark only — in-app chrome under 28px, light theme
//   sidebar   app-chrome treatment per spec §06: solid signal tile with
//             navy P, paper wordmark — dark theme chrome
//   mono      single-colour print
//   icon      tile only — the small-size mark
//
// The mark is a home link where clickable; never add hover transforms or
// colour shifts to it (spec "Interactions").
const SRC = {
  primary: '/logo.svg',
  reversed: '/wordmark-dark.svg',
  short: '/brand/lockup-short.svg',
  sidebar: '/brand/app-sidebar.svg',
  mono: '/brand/lockup-mono.svg',
  icon: '/favicon.svg',
}

export default function Logo({ variant = 'primary', height = 32, style, alt = 'Properly' }) {
  return (
    <img
      src={SRC[variant] || SRC.primary}
      alt={alt}
      style={{ height, width: 'auto', display: 'block', ...style }}
    />
  )
}

// App-chrome mark: picks the spec's sidebar treatment on the dark theme
// and the standard short lockup on light.
export function ChromeLogo({ height = 26, style }) {
  const { darkMode } = useTheme()
  return <Logo variant={darkMode ? 'sidebar' : 'short'} height={height} style={style} />
}

// Tile-only chrome mark (collapsed nav rail): solid signal tile on dark,
// standard navy tile on light. The tile alone is the small-size mark.
export function ChromeIcon({ size = 30, style }) {
  const { darkMode } = useTheme()
  return (
    <img
      src={darkMode ? '/brand/icon-signal.svg' : '/monogram-dark.svg'}
      alt="Properly"
      style={{ width: size, height: size, display: 'block', ...style }}
    />
  )
}
